# $env:DATABASE_URL = "postgres://postgres:postgres@localhost:5432/goroadmap?sslmode=disable"
services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goroadmap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goroadmap"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  pgdata: